### ISSUE TITLE
Can we use this plugin on --no-prerender option?

### ISSUE THREAD

**Issue by azulkipli** [matthewlynch/preact-cli-plugin-critical-css#4]
Can we use this plugin on --no-prerender option?
How to check that this plugin really works?
Thanks

**Comment by matthewlynch** [comment]
Hi @azulkipli,

This plugin only works when prerendering so it wouldn't do anything if that option is set.

Can you explain what your use case is/what you'd like to be able to do?

You can create a new project using the default template and install this plugin if you'd like to test how it works:
```sh
$ preact create default test-project
$ npm i -D preact-cli-plugin-critical-css
```
then create a `preact.config.js` file in the `test-project` folder:
```js
// preact.config.js
const criticalCssPlugin = require('preact-cli-plugin-critical-css');

export default function(config, env, helpers) {
  criticalCssPlugin(config, env);
}
```
and then run a build: 
```sh
$ npm run build
```

**Comment by azulkipli** [comment]
Oh okay thanks
